#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Avenco"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 6


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Avenco - Creative Portfolio Theme for HUGO"


[params.global.image]
  enable = true
  cover__image = 'https://via.placeholder.com/1920x600' # Add global cover image (This field adds a background to the top and bottom of the site.)

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 3
    hasChildren = true

      [[menu.main]]
      parent = "Pages"
      name = "About"
      url = "/about/"
      weight = 1

      [[menu.main]]
      parent = "Pages"
      name = "Elements"
      url = "/elements/"
      weight = 2

  # Call to action button
  [params.menu.button]
    cta__button__text = "Get in touch"


  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "James Clayton"
    author__title = "Hello I’m James Clayton"
    author__bio = "Art Director & Graphic Designer based in Australia, crafting beautiful and functional websites and mobile apps. When I’m not working, I’m probably listening to relaxing music or traveling somewhere."
    author__image = "https://via.placeholder.com/600x600"
    author__avatar = "https://via.placeholder.com/200x200"
    button__text = "See my works"


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = true
    projects__title= "Latest <span class='text-span'>Works</span>" # Add a 'text-span' class to highlight text.
    projects__description= "I shows only the best websites and portfolios built completely with passion, simplicity & creativity!"


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial__title = "My Happy <span class='text-span'>Clients</span>" # Add a 'text-span' class to highlight text.
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Zaire Baptista"
    image = "https://via.placeholder.com/250x250"
    designation = "Traveler"
    content = "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  [[params.testimonial_item]]
    name = "Ann Philips"
    image = "https://via.placeholder.com/250x250"
    designation = "Designer"
    content = "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  [[params.testimonial_item]]
    name = "Roger Bergson"
    image = "https://via.placeholder.com/250x250"
    designation = "CEO, Founder"
    content = "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  [[params.testimonial_item]]
    name = "Julie Arnold"
    image = "https://via.placeholder.com/250x250"
    designation = "Full stack developer"
    content = "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Recent <span class='text-span'>Blog</span> Posts" # Add a 'text-span' class to highlight text.
    blog__description = ""


  #-------------------------------
  # Contact Settings
  [params.contact]
    enable = true
    contact__email = "your@email.com" # Add your form_id
    contact__title = "<span class='text-span'>Get</span> in touch" # Add a title to your form
    contact__description = "Avenco comes with a built-in contact form." # Add a description to your form

    # NOTE
    # Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp__title = "<span class='text-span'>Join</span> my mailing list" # Add your title
    mailchimp__text = "Get the best inspiration and, cool stuff about design!" # Add descriptions to the form. If you want to use more than one sentence, be sure to separate them with a comma.
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__button__text = "Subscribe" # Add your button text

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo


  #-------------------------------
  # Footer Settings
  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-codepen"
    name = "Codepen"
    link = "https://codepen.io"

  [[params.social]]
    icon = "ion-logo-vimeo"
    name = "Vimeo"
    link = "https://vimeo.com"

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-facebook"
  #   name = "Facebook"
  #   link = "https://facebook.com"

  # Other icons can be found at https://ionicons.com/v4/


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false