baseURL = 'https://devreldiaries.com/'
languageCode = 'en-us'
title = 'DevRel 🥑 Diaries'
theme = "avenco"
author = "DevRel Diaries"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
rssLimit = 25

[params]
  logo = "/images/DevAdv.png"
  description = "DevRel Diaries: Where Real DevRel Meets Real Life"

# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "Policies"
    name = "Policies"
    url = "/policies/"
    weight = 2
    hasChildren = true

    [[menu.main]]
      parent = "Policies"
      name = "Code of Conduct"
      url = "/code_of_conduct/"
      weight = 1

    [[menu.main]]
      parent = "Policies"
      name = "Privacy Policy"
      url = "/privacy_policy/"
      weight = 2

  [[menu.main]]
    identifier = "Contribute"
    name = "Contribute"
    url = "/contribute/"
    weight = 3
    hasChildren = true

    [[menu.main]]
      parent = "Contribute"
      name = "How to Contribute"
      url = "/contribute/"
      weight = 1

    [[menu.main]]
      parent = "Contribute"
      name = "Submit Your Story"
      url = "/submit/"
      weight = 2

    [[menu.main]]
      parent = "Contribute"
      name = "Submit a Quote"
      url = "/submit_quote/"
      weight = 3

  [[menu.main]]
    identifier = "stories"
    name = "Stories"
    url = "/posts/"
    weight = 4
    hasChildren = true

  [[menu.main]]
    parent = "Pages"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    parent = "Pages"
    name = "Stories"
    url = "/posts/"
    weight = 2

  # Call to action button
  [params.menu.button]
    cta__button__text = "Get in touch"

  # Author Settings
  [params.author]
    author__name = "DevRel Diaries"
    author__title = "<span class='text-span'>Hello,</span> We are DevRel Diaries"
    author__bio = "We are collecting and sharing real-life stories about mental health from real-life Developer Relations Professionals. Please, share your story with us! See [how you can contribute](/about/)."
    author__image = "/images/bethany-randall-XgZ0et0FUS8-unsplash.jpg"
    author__avatar = "/images/DevAdv.png"
    button__text = "See our stories"

  # Projects Settings
  [params.projects]
    enable = false
    projects__title= "<span class='text-span'>How</span> to contribute a Story to the Diaries"
    projects__description= ""

  # Blog Section
  [params.blog]
    enable = true
    blog__title = "<span class='text-span'>Recent</span> Stories "
    blog__description = "Read the latest diary entries"

  # Contact Settings
  [params.contact]
    enable = true
    contact__email = "diaries@devreldiaries.com"
    contact__title = "<span class='text-span'>Get</span> in touch"
    contact__description = "Contribute your story!"

  # Newsletter Settings
  [params.mailchimp]
    enable = false
    mailchimp__title = "<span class='text-span'>Join</span> my mailing list"
    mailchimp__text = "Get the best inspiration and, cool stuff about design!"
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__button__text = "Subscribe"


# Comment Section (Disqus)
  [params.disqus]
    enable = false
    disqusShortname = "anvodstudio-demo"

  # Footer Settings
  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com/devreldiaries"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com/davidgs/dev-rel-diaries"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false


# Testimonials Section
  [params.testimonials]
    enable = true
    testimonial__title = "<span class='text-span'>Insights</span> and Quotes"
    testimonial__description = "Short quotes and insights from DevRel Professionals"

  [[params.testimonial_item]]
    name = "David G. Simmons"
    link="https://twitter.com/davidgsIoT"
    image = "/posts/avatars/profile-pic.png"
    designation = "Head of Developer Advocacy"
    content = "If a friend comes and says \"hey, I've noticed these changes in you, are you ok?\" You should do 2 things:<ol class=\"client-text\"><li> Be honest with them about how you're REALLY doing.</li><li> Tell them that you love them because they may have just saved your life.</li></ol>"


  [[params.testimonial_item]]
    name = "I'm a fucking frog"
    link = ""
    image = "/posts/avatars/avocato2.png"
    designation = "Kermit"
    content = "<p>Being green isn&rsquo;t fucking easy</p>
"
