---
title: <span class='text-span'>I'm</span> in Love with a Pig
date: 2022-10-27
image: posts/i'm-in-love-with-a-pig/images/header-mohamed-nohassi-odxB5oIG_iA-unsplash.jpg
image_caption: Save Me
description: I'm a frog
author: Kermit The Frog
author_avatar: /images/DevAdv.png
---

# <span class='text-span'>It</span> isn't easy

Being Green
 ![image](http://localhost/dev-rel-diaries-server/tmp/31lkPwWbj64zwi6J0J8mC7TlzkU=/i'm-in-love-with-a-pig/images/post-bandaid.png) 