---
title: <span class='text-span'>A</span> total test
date: 2022-10-12
image: posts/a-total-test/images/header-DevRelLife.png
image_caption: Living that DevRel Life
description: A testing description
author: Hank Aaron
author_twitter: davidgsIoT
author_avatar: /posts/a-total-test/images/avatar-profile-pic.png
---

## <span class='text-span'>Don't</span> use these words

Stop using words like this  ![image](https://devreldiaries.com/dev-rel-diaries-server/tmp/RMgJKpuWqquA3vR_X5GkZE37lxw=/a-total-test/images/post-simple.png) 

They are *unhelpful* and make people feel **stupid**